services:
  chatapp:
    container_name: ChatWithIGEM
    build: .
    env_file: .env
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - qdrant
    environment:
      - qdrant_HOST=qdrant
    volumes:
      - ./src:/src
      - ./scripts:/scripts

  qdrant:
      image: qdrant/qdrant:v1.9.5
      restart: always
      container_name: qdrant
      ports:
        - "6333:6333"  # Expose the HTTP API port
        - "6334:6334"  # Expose the Prometheus metrics port
      volumes:
        - ./qdrant:/qdrant/storage
